export const global = {
    host: 'http://localhost:5000',
    port: '',
    github: 'https://github.com/vutuanhai237',
    youtube: 'https://www.youtube.com/channel/UCeT_vjcZwjXEzTOFtEX-PZg/',
    linkedin: 'https://www.linkedin.com/in/vutuanhai237/',
    facebook: 'https://www.facebook.com/vutuanhai237',
}
export const eng = {
    crop: 'Crop',
    focus_on_mouth: 'Focus on mouth',
    the_video_has_been_processed_completely: 'The video has been processed completely!',
    ok: 'OK',
    upload_and_crop: 'Upload & crop',
    alert: 'Alert',
    take_a_shot: 'take a shot',
    concat_video: 'Concat video',
    processed_video: 'Processed video',
    get: 'Get',
    get_concat_video: 'Get concat video',
    get_processed_video: 'Get processed video',
    select_model: 'Select model',
    process: 'Process',
    notification: 'Notification',
    server_is_loading_model: 'Server is loading model',
    processed_image: 'Processed image',
    delete: 'Delete',
    upload: 'Upload',
    download: 'Download',
    your_image_or: 'your image or',
    capture: 'Capture',
    cycleGAN: 'CycleGAN',
    pix2pix: 'Pix2Pix',
    monadotory: 'Monadotory',
    braces2teeth: 'Braces2teeth',
    braces2teeth_video: 'Braces2teeth Video',
    research_notebook: 'Research notebook',
    life_notebook: 'Life notebook',
    The_resonsitory_of_my_knowledges: 'The resonsitory of my knowledges',
    please_choose_one_model: 'Please choose one model'
}